### ISSUE TITLE
confirm files with authors

### ISSUE THREAD

**Issue by timm** [researchart/re19#11]
Please got to https://github.com/researchart/re19/tree/master/submissions and conform your files are here and I the right directory

- [x] Alessio Ferrari  alessioferrari
- [x] Tim Rietz    
- [x] Larissa Chazette 
- [x]  Hugo Villamizar  hrguarinv 
- [ ] James Tizard  jtiz003
- [x] Daniel Dietsch |  danieldietsch
- [x] Fatma Başak Aydemir | aydemirfb
- [x] Ally S. Nyamawe  nyamawe
- [x] Andreas Vogelsang andivogelsang

**Comment by tr-evo** [comment]
> * [ ]  Alessio Ferrari  alessioferrari
> * [x]  Tim Rietz
> * [ ]  Larissa Chazette
> * [ ]   Hugo Villamizar  hrguarinv
> * [ ]  James Tizard  jtiz003
> * [x]  Daniel Dietsch |  danieldietsch
> * [ ]  Fatma Başak Aydemir | aydemirfb
> * [ ]  Ally S. Nyamawe  nyamawe

**Comment by timm** [comment]
@tr-evo : I aded u as a collaborator. can u check now?

**Comment by larissamp** [comment]
I also couldn't get the checkbox to work, but my files are also there

**Comment by larissamp** [comment]
Here the checkboxes also don't work.
My files are there though. :)

**Comment by nyamawe** [comment]
The checkboxes are not working for me, so I can't check. However, my files are OK.

**Comment by timm** [comment]
having trouble finding emails for James Tizard . tizmd@iid.ad.jp is not working

![image](https://user-images.githubusercontent.com/29195/60602937-c51f8f80-9d82-11e9-92f9-536b4aade6d9.png)


now trying jtiz003@aucklanduni.ac.nz

**Comment by neilernst** [comment]
JTiz confirmed via email
