### ISSUE TITLE
confirm ids with authors

### ISSUE THREAD

**Issue by timm** [researchart/re19#12]
are the following GitHub ids right? (Tim and Larissa, need help)

- [x] Alessio Ferrari  alessioferrari
- [x] Tim Rietz    tr-evo
- [x] Larissa Chazette  larissamp,
- [x]  Hugo Villamizar  hrguarinv 
- [x] James Tizard  jtiz003
- [x] Daniel Dietsch |  danieldietsch
- [x] Fatma Başak Aydemir | aydemirfb
- [x] Ally S. Nyamawe  nyamawe
- [x] Andreas Vogelsang andivogelsang

**Comment by tr-evo** [comment]
This is Tim Rietz (tr-evo)

**Comment by timm** [comment]
@tr-evo : I added u as a collaborator. can u check now?

t

**Comment by larissamp** [comment]
Hey! Larissa Chazette here 🙋‍♀️

**Comment by larissamp** [comment]
Checkboxes also don't seem to work here

**Comment by nyamawe** [comment]
This is Ally, my ID is correct.

**Comment by timm** [comment]
sorry @larissamp, I had not added you as a collaborator. 🙇 

please tick now (if the files are right).

**Comment by timm** [comment]
dear @jtiz003 having trouble finding your emails for James Tizard . tizmd@iid.ad.jp is not working

trying 

jtiz003@aucklanduni.ac.nz
--
