### ISSUE TITLE
Review submission 119nyamawa

### ISSUE THREAD

**Issue by neilernst** [researchart/re19#14]

**Comment by wagnerst** [comment]
Hi @nyamawe ,
I cannot get your Python code to run. I understand that I need to run create_dataset.py first. But it expects a final_dataset.pickle file that is not there. Please advise.

Thanks,
Stefan

**Comment by nyamawe** [comment]
Hi, Stefan,

Attached is the zip file containing the required pickle files. Please, accept my apologies for not including them in the first place. The rest of the pickle files required will be generated by the code. Kindly, let me know if I would be required to clarify anything.
[Pickles.zip](https://github.com/researchart/re19/files/3376454/Pickles.zip)

**Comment by nyamawe** [comment]
Hi, Stefan,
I have added the pickle files as a zip file to my submission. 
To get rid of an error you mentioned, please comment line 31 of the same source file. Hope that will work. Thanks.

**Comment by wagnerst** [comment]
Hi @nyamawe ,

if I comment out line 31, I get the following output from running 'featuresets_generation.py":
`features of length  5000  is loaded.....
Traceback (most recent call last):
  File "featuresets_generation.py", line 125, in <module>
    make_featuresets(features)
  File "featuresets_generation.py", line 83, in make_featuresets
    documents_f = open("./T&T/testing.pickle", "rb")
FileNotFoundError: [Errno 2] No such file or directory: './T&T/testing.pickle'`

Can you please check that this is fully running? The Available badge requires that this is exercisable and that there is evidence of V&V. Both are not apparent to me at this point.

**Comment by neilernst** [comment]
@nyamawe we will be making decisions and finalizing badges very soon (today or tomorrow), so please stay engaged on this issue

**Comment by nyamawe** [comment]
Hi, Stefan,
Sorry for the late reply, in the attached zip I have created the required directories and the associated files.
[nyamaweally@yahoo.com + FR-Refactor + PaperID-119.zip](https://github.com/researchart/re19/files/3388815/nyamaweally%40yahoo.com.%2B.FR-Refactor.%2B.PaperID-119.zip)

**Comment by timm** [comment]
Dear @wagnerst : please clarify "cannt get to run". what platform were you trying?

dear @nyamawe : please comment: re code not running: is this a missing file thing or a platform thing.

Dear all-- we need to move to a decision on this asap. Currently, the status is "no badge", which is something I really want to change. Please resolve at your earliest convenience.

**Comment by nyamawe** [comment]
Dear @timm 
There were missing files and some directories were not created. I addressed this issue in the last zip file I shared.

**Comment by wagnerst** [comment]
Thanks for the update @nyamaweally! Unfortunately, it still does not work. No I get the following error:
`FileNotFoundError: [Errno 2] File b'./dataset/TextPreprocessed.csv' does not exist: b'./dataset/TextPreprocessed.csv'`
when running multi-label_classifiers.py.
I am on macOS using Python 3. 
Have you tried running the code just directly from your unzipped file?
I only have to run one python script after the other as they are in the directory (alphabetically ordered), correct?

**Comment by nyamawe** [comment]
Dear @wagnerst 
I have just renamed the source code files starting with the order number for your convenience. I believe there is no problem with the platform you are using. I am failing to upload the zip file here, so please find it from here: 
https://github.com/nyamawe/FR-Refactor/tree/master

Sorry for the inconvenience.

**Comment by nyamawe** [comment]
In case the above URL won't work, here is the same zip file.

[nyamaweally@yahoo.com + FR-Refactor + PaperID-119 (2).zip](https://github.com/researchart/re19/files/3391503/nyamaweally%40yahoo.com.%2B.FR-Refactor.%2B.PaperID-119.2.zip)

**Comment by wagnerst** [comment]
OK, thanks. This is working. Please exchange the version here with your new version and make it publicly available with a DOI (for example at Zenodo). Then I am happy to recommend Available.

**Comment by nyamawe** [comment]
I am glad to hear that Stefan, let me do it. Thank you so much for your cooperation.

**Comment by nyamawe** [comment]
But I have already created a public repository on GitHub, is that not enough.?

**Comment by wagnerst** [comment]
No. A GitHub repo is not a long-term archive. You can create a tag in GitHub and import that directly into Zenodo. This will give you the DOI. Very simple.

**Comment by nyamawe** [comment]
Noted with thanks.

**Comment by nyamawe** [comment]
Dear Stefan,
I have already uploaded our artifacts at Zenodo. The given DOI is 10.5281/zenodo.3335978.

**Comment by wagnerst** [comment]
OK, perfect! Thank you!

**Comment by timm** [comment]
so I think we have terminated here. label="available"
